### ISSUE TITLE
NFFS removed from Zephyr

### ISSUE THREAD

**Issue by philips77** [JuulLabs-OSS/mcumgr-android#73]
Support for NFFS was removed from Zephyr: https://docs.zephyrproject.org/latest/releases/release-notes-2.2.html#removed-apis-in-this-release
It was replaced by LittleFS, which change the partition from *nffs* to *lfs*:
https://github.com/apache/mynewt-mcumgr/pull/62

**Comment by philips77** [comment]
References to NFFS in this reop: https://github.com/JuulLabs-OSS/mcumgr-android/search?q=nffs

**Comment by bgiori** [comment]
Thanks, I will hop on this and figure something out...

**Comment by philips77** [comment]
I don't know how it's in mynewt. In our fork I just replaced that with *lfs*: https://github.com/NordicSemiconductor/Android-nRF-Connect-Device-Manager/commit/241aa9ecd0e9b0e3b09f399e4b779c3daa8ae5c5

**Comment by bgiori** [comment]
@philips77 I followed your lead here and changed everything from nffs -> lfs
