### ISSUE TITLE
Sample does not work with Zephyr SMP server

### ISSUE THREAD

**Issue by dakejahl** [JuulLabs-OSS/mcumgr-android#89]
The `sample` provided in this repo does not work with Zephyr's smp_svr sample. The `go` implementation does work for me. Any ideas what the issue could be? The output from the sample is
```
I/McuMgrBleTransport: Connected to FA:1D:5E:72:9D:C3
D/McuMgrBleTransport: wait(1600)
V/McuMgrBleTransport: Discovering services...
D/McuMgrBleTransport: gatt.discoverServices()
D/BluetoothGatt: discoverServices() - device: FA:1D:5E:72:9D:C3
D/BluetoothGatt: onSearchComplete() = Device=FA:1D:5E:72:9D:C3 Status=0
I/McuMgrBleTransport: Services discovered
E/McuMgrBleTransport: Device does not support SMP service
W/McuMgrBleTransport: Device is not supported
V/McuMgrBleTransport: Disconnecting...
D/McuMgrBleTransport: gatt.disconnect()
D/BluetoothGatt: cancelOpen() - device: FA:1D:5E:72:9D:C3
D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=9 device=FA:1D:5E:72:9D:C3
D/McuMgrBleTransport: [Callback] Connection state changed with status: 0 and new state: 0 (DISCONNECTED)
I/McuMgrBleTransport: Disconnected
D/McuMgrBleTransport: gatt.close()
```
**Target**
nrf52840dk
**Firmware**
https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/subsys/mgmt/mcumgr/smp_svr
**go implementation**
https://github.com/apache/mynewt-mcumgr-cli

**Comment by philips77** [comment]
This may be the phone caching old services. Restart Bluetooth on the phone and try again. Or, in nRF Connect app for Android, connect to your device and select menu->Refresh services. Then try again.

**Comment by dakejahl** [comment]
That did it! Thank you so much! I am just wandering my way through open
source and bluetooth is a new one for me :-)
